name: Add Branch Protection

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository (owner/repo format)'
        required: true
      branch_pattern:
        description: 'Branch pattern'
        required: true

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Add Branch Protection Rule
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.event.inputs.repository }}
        BRANCH_PATTERN: ${{ github.event.inputs.branch_pattern }}
      run: |
        OWNER=$(echo "$REPOSITORY" | cut -d'/' -f1)
        REPO=$(echo "$REPOSITORY" | cut -d'/' -f2)
        curl -X PUT \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$OWNER/$REPO/branches/$BRANCH_PATTERN/protection \
          -d '{
            "required_status_checks": null,
            "enforce_admins": true,
            "required_pull_request_reviews": {"required_approving_review_count": 1},
            "restrictions": null
          }'
